package projetoa3.TelasToten;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Alana
 */
public class Lanches extends javax.swing.JFrame {

    /**
     * Creates new form Lanches
     */
    public Lanches() {
        setTitle("LANCHES");
        initComponents();
     getContentPane().setBackground(new java.awt.Color(255,145,77));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVoltar = new javax.swing.JButton();
        btnCancelarPedido = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BtnCoxinha = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BtnBeirute = new javax.swing.JButton();
        BtnHamburguer = new javax.swing.JButton();
        BtnJoelho = new javax.swing.JButton();
        BtnMisto = new javax.swing.JButton();
        BtnNatural = new javax.swing.JButton();
        BtnMortadela = new javax.swing.JButton();
        BtnTorta = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lanches");

        btnVoltar.setBackground(new java.awt.Color(255, 255, 248));
        btnVoltar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnCancelarPedido.setBackground(new java.awt.Color(255, 51, 51));
        btnCancelarPedido.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnCancelarPedido.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarPedido.setText("Cancelar Pedido");
        btnCancelarPedido.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCancelarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPedidoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        BtnCoxinha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LanchesImagens/coxinha2.jpg"))); // NOI18N
        BtnCoxinha.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Coxinha", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        BtnCoxinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCoxinhaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Lanches e Salgados");

        BtnBeirute.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LanchesImagens/beirute2.jpg"))); // NOI18N
        BtnBeirute.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Beirute", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        BtnBeirute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBeiruteActionPerformed(evt);
            }
        });

        BtnHamburguer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LanchesImagens/Hamburguer2.jpg"))); // NOI18N
        BtnHamburguer.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hamburguer", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        BtnHamburguer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHamburguerActionPerformed(evt);
            }
        });

        BtnJoelho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LanchesImagens/joelho.jpg"))); // NOI18N
        BtnJoelho.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Joelho/ Italiano", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        BtnJoelho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnJoelhoActionPerformed(evt);
            }
        });

        BtnMisto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LanchesImagens/MistoQuente2.jpg"))); // NOI18N
        BtnMisto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Misto quente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        BtnNatural.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LanchesImagens/sanduiche natural2.jpg"))); // NOI18N
        BtnNatural.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sanduiche Natural", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        BtnNatural.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNaturalActionPerformed(evt);
            }
        });

        BtnMortadela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LanchesImagens/sanduicheMortadela2.jpg"))); // NOI18N
        BtnMortadela.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sanduiche mortadela", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        BtnMortadela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMortadelaActionPerformed(evt);
            }
        });

        BtnTorta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LanchesImagens/TortaSalgada.jpg"))); // NOI18N
        BtnTorta.setToolTipText("");
        BtnTorta.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Torta Salgada", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LanchesImagens/Novo__1_-removebg-preview (1).png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(711, 711, 711)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(88, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnVoltar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(332, 332, 332))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCancelarPedido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnMisto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnCoxinha))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnNatural, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnBeirute))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnHamburguer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnMortadela))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnJoelho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnTorta))))
                .addContainerGap(95, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnVoltar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnBeirute, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnCoxinha))
                        .addComponent(BtnJoelho, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(BtnHamburguer, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnMisto, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnNatural)
                            .addComponent(BtnMortadela))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BtnTorta)
                        .addGap(32, 32, 32)))
                .addComponent(btnCancelarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed

         TipoPedidoToten vs = new TipoPedidoToten();
         vs.setVisible(true);  
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnCancelarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPedidoActionPerformed
        cancelarPedido();
    }//GEN-LAST:event_btnCancelarPedidoActionPerformed

    private void BtnCoxinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCoxinhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCoxinhaActionPerformed

    private void BtnBeiruteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBeiruteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnBeiruteActionPerformed

    private void BtnHamburguerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHamburguerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnHamburguerActionPerformed

    private void BtnJoelhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnJoelhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnJoelhoActionPerformed

    private void BtnNaturalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNaturalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnNaturalActionPerformed

    private void BtnMortadelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMortadelaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnMortadelaActionPerformed

    
      public void cancelarPedido(){
        
        CancelarPedidoToten vs = new CancelarPedidoToten();
         vs.setVisible(true);  
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lanches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lanches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lanches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lanches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lanches().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBeirute;
    private javax.swing.JButton BtnCoxinha;
    private javax.swing.JButton BtnHamburguer;
    private javax.swing.JButton BtnJoelho;
    private javax.swing.JButton BtnMisto;
    private javax.swing.JButton BtnMortadela;
    private javax.swing.JButton BtnNatural;
    private javax.swing.JButton BtnTorta;
    private javax.swing.JButton btnCancelarPedido;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    
}
